feat: return reasons and remove from args.
optimizely/csharp-sdk pull request #255
Opened 2020-12-23 21:06 UTC by msohailhussain

## Summary
- returning reasons and removed from args
- added overloaded operator in DecisionReasons
- Now only one class is using DecisionReasons, toReport filters based on the DecisionOptions.

## Test plan
- All unit tests and FSC must pass.

2021-01-04 21:28 UTC, jaeopt requested changes
Overall looks good. 
I suggest to add tests validating core messages of reasons returned from decision to make sure reason collecting works as expected. See my comments.

2021-01-04 21:28 UTC, jaeopt commented on OptimizelySDK/Bucketing/DecisionService.cs
> +                    reasons += variationResult.DecisionReasons;
Move this line to before line 489

2021-01-04 21:28 UTC, jaeopt commented on OptimizelySDK/Optimizely.cs
> +            return DecisionService.GetForcedVariation(experimentKey, userId, config)?.ResultObject;
remove "?". Result never returns null.

2021-01-04 21:28 UTC, jaeopt commented on OptimizelySDK/Optimizely.cs
> +            var decisionSource = flagDecisionResult?.ResultObject?.Source ?? FeatureDecision.DECISION_SOURCE_ROLLOUT;
```suggestion
            var decisionSource = flagDecisionResult.ResultObject?.Source ?? FeatureDecision.DECISION_SOURCE_ROLLOUT;
```

2021-01-04 21:28 UTC, jaeopt commented on OptimizelySDK/Optimizely.cs
> +            if (decisionResult?.ResultObject?.Source == FeatureDecision.DECISION_SOURCE_FEATURE_TEST)
```suggestion
            if (decisionResult.ResultObject?.Source == FeatureDecision.DECISION_SOURCE_FEATURE_TEST)
```

2021-01-04 21:28 UTC, jaeopt commented on OptimizelySDK/Optimizely.cs
> +                { "source", decisionResult?.ResultObject?.Source },
```suggestion
                { "source", decisionResult.ResultObject?.Source },
```

2021-01-04 21:43 UTC, msohailhussain commented on OptimizelySDK/Bucketing/DecisionService.cs
> +            if (variationResult?.ResultObject != null)
yes , true.

2021-01-04 21:43 UTC, msohailhussain commented on OptimizelySDK/Bucketing/DecisionService.cs
> +                if (variationResult != null && variationResult.ResultObject?.Key != null)
+1

2021-01-07 00:29 UTC, jaeopt approved these changes
LGTM with nits

2021-01-07 00:29 UTC, jaeopt commented on OptimizelySDK/Bucketing/DecisionService.cs
> +                    reasons += variationResult?.DecisionReasons;
```suggestion
                    reasons += variationResult.DecisionReasons;
```

2021-01-07 00:29 UTC, jaeopt commented on OptimizelySDK/Bucketing/DecisionService.cs
> +                reasons += variationResult?.DecisionReasons;
```suggestion
                reasons += variationResult.DecisionReasons;
```

2021-01-20 21:06 UTC, merged