TESTING - Unique experiment key
optimizely/csharp-sdk pull request #267
Opened 2021-07-08 23:16 UTC by msohailhussain

## Summary
- The "what"; a concise description of each logical change
- Another change

The "why", or other context.

## Test plan

## Issues
- "THING-1234" or "Fixes #123"

2021-07-09 17:01 UTC, keppel2 approved these changes

2021-07-09 17:01 UTC, keppel2 commented on OptimizelySDK/ProjectConfig.cs
> +        /// Get the Variation from the Key/ID
"key" and "id" have different capitalization in the various comments.

2021-07-09 17:02 UTC, Mat001 approved these changes
No unit tests needed?

2021-07-09 17:21 UTC, msohailhussain commented
> No unit tests needed? @msohailhussain

good point, yes we need to add unit tests but I think I can add a separate ticket. Need to think about some scenarios.

2021-07-12 22:33 UTC, jaeopt requested changes
fix errors

2021-07-12 22:33 UTC, jaeopt commented on OptimizelySDK/Config/DatafileProjectConfig.cs
> +        public Dictionary<string, Dictionary<string, Variation>> VariationKeyMapByExperimentId { get { return _VariationKeyMap; } }
Shouldn't it return _VariationKeyMapByExperimentId, instead of _VariationKeyMap?

2021-07-12 22:33 UTC, jaeopt commented on OptimizelySDK/Config/DatafileProjectConfig.cs
> +        public Dictionary<string, Dictionary<string, Variation>> VariationKeyIdByExperimentId { get { return _VariationKeyMap; } }
same here

2021-07-13 16:12 UTC, jaeopt approved these changes
LGTM

2021-07-15 16:56 UTC, merged