Refact: Refactored Forced decision
optimizely/csharp-sdk pull request #287
Opened 2021-11-30 15:54 UTC by mnoman09

## Summary
- Refactored code and fixed some minor issues. 

## Test plan
All FSC and unit tests should pass

2021-11-30 18:46 UTC, msohailhussain commented on OptimizelySDK/OptimizelyUserContext.cs
> +        public OptimizelyUserContext(Optimizely optimizely, string userId, UserAttributes userAttributes, ForcedDecisionsStore forcedDecisionsStore, IErrorHandler errorHandler, ILogger logger)
Do we really need this constructor method? @jaeopt  a question for you.

2021-11-30 18:51 UTC, msohailhussain commented on OptimizelySDK/ForcedDecisionsStore.cs
> +    public class ForcedDecisionsStore
Unit tests are already covered for this class as transitive dependency. But I will appreciate @mnoman09 to write unit tests.

2021-12-01 00:00 UTC, jaeopt requested changes
Refactor looks good! Some changes suggested.

2021-12-01 19:07 UTC, dustin-sier commented
LGTM, appreciate the changes

2021-12-02 21:58 UTC, jaeopt approved these changes
LGTM

2021-12-02 23:14 UTC, merged