chore: prepare for release 3.11.0
optimizely/csharp-sdk pull request #293
Opened 2022-01-06 15:08 UTC by mnoman09

## Summary
- Prepare for release 3.11.0

2022-01-06 17:12 UTC, jaeopt requested changes
The doc url to "Forced Decision methods" is incorrect - missing "-csharp" at the end.

2022-01-06 22:51 UTC, msohailhussain commented on CHANGELOG.md
> +- For details, refer to our documentation pages: [OptimizelyUserContext](https://docs.developers.optimizely.com/full-stack/v4.0/docs/optimizelyusercontext-csharp) and [Forced Decision methods](https:
```suggestion
- For details, refer to our documentation pages: [OptimizelyUserContext](https://docs.developers.optimizely.com/full-stack/v4.0/docs/optimizelyusercontext-csharp) and [Forced Decision methods](https://docs.developers.optimizely.com/full-stack/v4.0/docs/forced-decision-methods-csharp).
```

2022-01-06 23:07 UTC, jaeopt approved these changes
LGTM

2022-01-07 20:03 UTC, msohailhussain approved these changes
lgtm

2022-01-07 20:03 UTC, merged