[FSSDK-9090] Default instantiation of OdpManager for Optimizely constructors
optimizely/csharp-sdk pull request #347
Opened 2023-04-17 21:46 UTC by mikechu-optimizely

## Summary
- Fix OdpManager not having a default instantiation in `Optimizely` client

`OptimizelyFactory` provides a default which is desirable.  The `Optimizely` constructors should follow this.

## Test plan

- Add covering and passing unit test for `Optimizely`
- FSC integration tests should continue to pass

## Issues
- FSSDK-9090

2023-04-18 14:20 UTC, andrewleap-optimizely approved these changes
LGTM (with small nit)

2023-04-18 14:20 UTC, andrewleap-optimizely commented on OptimizelySDK/Optimizely.cs
> +                ?.ResultObject;
I like the use of the leading period in method chaining- what do you think about leaving the null conditional operator on the previous line, grouping it with its relevant method?

2023-04-18 15:37 UTC, andrewleap-optimizely commented on OptimizelySDK/Optimizely.cs
> +                ?.ResultObject;
🤷‍♂️ you win some, you lose some

2023-04-20 00:37 UTC, mnoman09 requested changes
Overall changes lgtm. But how are we going to disable the odp? Previously we assumed that if user is not passing odpManager then it will be considered as disabled. In my opinion if someone is using OptimizelyFactory to initialize Optimizely then odpManager should be enabled by default otherwise do not initialize it and consider it disabled. 
@jaeopt What do you suggest?

2023-04-20 15:58 UTC, jaeopt commented
> I have a question. How are we going to disable the odp? Previously we assumed that if user is not passing odpManager then it will be considered as disabled. In my opinion if someone is using OptimizelyFactory to initialize Optimizely then odpManager should be enabled by default otherwise do not initialize it and consider it disabled. @jaeopt What do you suggest?

ODP will be enabled unless they

2023-04-20 16:12 UTC, mikechu-optimizely commented
@mnoman09 I updated the https://github.com/optimizely/csharp-testapp/pull/83

2023-04-20 16:13 UTC, mikechu-optimizely commented
Is it ok to have this PR open @jaeopt given my change to the test app to support FSC?

2023-04-20 16:26 UTC, jaeopt commented
> Is it ok to have this PR open @jaeopt given my change to the test app to support FSC?

@mikechu-optimizely oops, did I close the PR? I was wondering my comment has been broken and not realized I closed it by mistake. Sorry :)

2023-04-20 19:58 UTC, mikechu-optimizely commented
Sweet. Passing now.  I just hope I satisifed @mnoman09 's question to get a LGTM

2023-04-24 12:58 UTC, mikechu-optimizely commented
Hey @mnoman09, I think you might be out, but I'm going to go ahead and merge this change.  DM me if you wanna talk more about it.  I'm happy to open more PRs to get it right.

2023-04-24 12:59 UTC, merged