[FSSDK-9128] fix: Handle ODP INVALID_IDENTIFIER_EXCEPTION code
optimizely/csharp-sdk pull request #348
Opened 2023-04-24 21:02 UTC by mikechu-optimizely

## Summary

Support a new format for ODP `InvalidIdentifierException` (when SDK fetches segments with a non-registered userId).

```
       "extensions": {
            "code": "INVALID_IDENTIFIER_EXCEPTION",
            "classification": "DataFetchingException"
       }
```

## Test plan
- Added unit tests to cover the new response format.
- Existing unit tests should pass
- FSC should continue to pass

## Issues
- FSSDK-9128

2023-04-24 22:12 UTC, jaeopt requested changes
I do not see a logic change to provide proper error message for INVALID_IDENTIFIER_EXCEPTION. Can you check again?

2023-04-25 12:44 UTC, mikechu-optimizely commented
> I do not see a logic change to provide proper error message for `INVALID_IDENTIFIER_EXCEPTION`. Can you check again?

I'm not handling any specific ODP exceptions specially. I'm simply concatenating all current and future messages returned from Zaius (via `.ToString`) into one `errors`: string in [OdpSegmentApiManager.cs](https://github.com/optimizely/csharp-sdk/blob/mike/invalid-identifier/OptimizelySDK/Odp/OdpSegmentApiManager.cs#L120) 

Should I check-for and return a specific new message when I receive the `code == INVALID_IDENTIFIER_EXCEPTION` or `classification == DataFetchingException`?

2023-04-25 16:19 UTC, jaeopt reviewed
Looks good!
The error "code" is optional. Can you check if we have a test case without code?

2023-04-25 16:19 UTC, jaeopt commented on OptimizelySDK.Tests/OdpTests/OdpSegmentApiManagerTest.cs
> +                            ""code"": ""SECOND_IGNORED_UNPLANNED_EXCEPTION"",
This "code" is optional. Wondering if we have a test case without "code".

2023-04-25 16:30 UTC, jaeopt commented on OptimizelySDK.Tests/OdpTests/OdpSegmentApiManagerTest.cs
> +                            ""code"": ""SECOND_IGNORED_UNPLANNED_EXCEPTION"",
ah I see no code in line 229.

2023-04-25 16:53 UTC, merged