[FSSDK-9486] maint: Update CI and publishing
optimizely/csharp-sdk pull request #356
Opened 2023-07-03 15:57 UTC by mikechu-optimizely

## Summary
- Large updates to C# CI workflow
- Add new trigger on release remote dispatch;  needs to be in master to test initial

Need to release branch v3.11.3 and taking the opportunity  to revamp DevOps

## Test plan

- No code paths changed, so unit, integration tests should continue to work.

## Issues
- FSSDK-9486

2023-07-03 18:22 UTC, mikechu-optimizely commented
This PR needs to be merged **BEFORE**
#357
#358

2023-07-06 21:50 UTC, jaeopt requested changes
Looks great! A couple of suggestions.

2023-07-06 21:50 UTC, jaeopt commented on .github/workflows/csharp.yml
> +      TRAVIS_COM_TOKEN: ${{ secrets.TRAVIS_COM_TOKEN }}
Can't we remove all this "TRAVIS" terms? I believe, we do not have any more dependencies onto TRAVIS.

2023-07-06 21:50 UTC, jaeopt commented on .github/workflows/csharp.yml
> +      TRAVIS_COM_TOKEN: ${{ secrets.TRAVIS_COM_TOKEN }}
Wondering why we can remove aws s3 for github actions. Can we add why in the PR summary for record?

2023-07-07 12:50 UTC, mikechu-optimizely commented
Later, I'll need to remove the CI and deployment secrets supporting AWS uploads.

2023-07-07 12:57 UTC, mikechu-optimizely commented
Temporarily closing to avoid CI runs

2023-07-07 23:38 UTC, jaeopt commented on .github/workflows/csharp.yml
> +      TRAVIS_COM_TOKEN: ${{ secrets.TRAVIS_COM_TOKEN }}
sounds good. we can remove all "TRAVIS" in a separate task.

2023-07-07 23:48 UTC, jaeopt approved these changes
LGTM - so I guess with this change, we now can remove the codesign repo completely?

2023-07-10 14:49 UTC, merged

2023-07-10 14:50 UTC, mikechu-optimizely commented
> LGTM - so I guess with this change, we now can remove the codesign repo completely?

@jaeopt I think we should archive it for sure, so it's not used.